### ISSUE TITLE
Catching exceptions

### ISSUE THREAD

**Issue by Ashen-MG** [TIS2021-FMFI/zaujem-o-sport#125]
Tento spôsob
try: ...
except Union[psycopg2.DatabaseError, DataError] as error: ....
zrejme nefunguje - testoval som to a na db chybe dostávam naviac takúto hlášku (napr. pri pridávaní krajiny pri porušení integritného obmedzenia):

<pre>
Traceback (most recent call last):
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\db\__init__.py", line 567, in addCountry
    "code": data["code"]})
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\psycopg2\extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flasgger\marshmallow_apispec.py", line 92, in dispatch_request
    return super(SwaggerView, self).dispatch_request(*args, **kwargs)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\verification\jwt\__init__.py", line 31, in decorated_function
    return f(*args, **kwargs)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\admin\endpoints\countries\__init__.py", line 10, in post
    ok = DB.addCountry(request.json)
  File "C:\Users\Martys\Projects\WorkProjects\sport\backend\db\__init__.py", line 581, in addCountry
    except Union[psycopg2.DatabaseError, DataError] as error:
TypeError: catching classes that do not inherit from BaseException is not allowed

</pre>

**Comment by Sabka** [comment]
ahoj, pri akom poruseni sa ti to podarilo ?

**Comment by Sabka** [comment]
okay, podarilo sa mi to nasimulovat, asi je nespravny sposob davat to do toho union, neviem z coho to vzniklo
